name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install qt5-qmake 
    - name: create build dir
      run: mkdir build && cd build
    - name: qmake
      run: /usr/bin/qmake ..
    - name: build
      run: make
